### ISSUE TITLE
Using The package on UWP application with .pbf extention files.

### ISSUE THREAD

**Issue by ImCarrot** [bertt/mapbox-vector-tile-cs#6]
Hi, I tried to use the the XAMARIN sample for UWP app from [here](https://github.com/ryanlowdermilk/VectorTilesWithXamarinMaps) as directed in the description. The issue I am facing is the MapFilter Common project is fetching data from the local directory, with extentions `.mvt` the vector tiles I want to deploy are of the format `.pbf` . Please help me on how can I achieve to implement the `.pbf` extention vector Tiles files on my map control. Also I want to get the tiles from my server instead of the local directories. could you please help.

**Comment by bertt** [comment]
. for using .pbf instead of .mvt: just change the files in the project resources and in app.cs
. for using tiles from server: add a tile web request mechanism, https://github.com/BruTile/BruTile is a good candidate

But better discuss this at the VectorTilesWithXamarinMaps repository, so closing here.
